--- 
abstract: A bundle to install all POE simple TCP/IP services modules.
author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.67
license: perl
meta-spec: 
  url: http://module-build.sourceforge.net/META-spec-v1.3.html
  version: 1.3
name: Bundle-POE-Simple-TCPIP-Services
no_index: 
  directory: 
    - inc
    - t
version: 1.01
