author: Chris Williams <chris@bingosnet.co.uk>
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Bundle-POE-Simple-TCPIP-Services
no_index: 
  directory: 
    - inc
    - t
version: 1.00
